### ISSUE TITLE
Reloading plugin raises "Command is already registered" on L481

### ISSUE THREAD

**Issue by PythonTryHard** [tandemdude/hikari-lightbulb#202]
### Steps to reproduce

1. Clone down https://github.com/PythonTryHard/repro (will be archived after issue closes)
2. Run `bot.py` from inside the directory

### Expected result

The bot reloading the extension normally.

### Actual result

```
➜ python .\bot.py
I 2022-02-02 16:08:17,474 lightbulb.app: Extension loaded 'repro.command.sanity'
I 2022-02-02 16:08:17,478 lightbulb.app: Extension unloaded 'repro.command.sanity'
Traceback (most recent call last):
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 481, in reload_extensions
    self.load_extensions(extension)
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 412, in load_extensions
    ext.load(self)
  File "F:\dev\remi\repro\command\sanity\__init__.py", line 10, in load
    bot.add_plugin(sanity_plugin)
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 814, in add_plugin
    self._add_command_to_correct_attr(command)
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 316, in _add_command_to_correct_attr
    raise errors.CommandAlreadyExists(
lightbulb.errors.CommandAlreadyExists: A prefix command with name or alias 'sanity' is already registered.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\dev\remi\repro\bot.py", line 30, in <module>
    bot.reload_extensions("repro.command.sanity")
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 485, in reload_extensions
    self.load_extensions(extension)
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 412, in load_extensions
    ext.load(self)
  File "F:\dev\remi\repro\command\sanity\__init__.py", line 10, in load
    bot.add_plugin(sanity_plugin)
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 814, in add_plugin
    self._add_command_to_correct_attr(command)
  File "F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\lightbulb\app.py", line 316, in _add_command_to_correct_attr
    raise errors.CommandAlreadyExists(
lightbulb.errors.CommandAlreadyExists: A prefix command with name or alias 'sanity' is already registered.
```

### System info

```shell
hikari-lightbulb (2.1.3)
hikari (2.0.0.dev105) [a3825788]
located at F:\dev\.env\remi-0WewpwuQ-py3.10\lib\site-packages\hikari
CPython 3.10.0 MSC v.1929 64 bit (AMD64)
Windows Sewa 10 10.0.19043 AMD64 Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
```

### Further info

When I first debugged the issue, I focused on `sys.modules` as I thought it held information on what are being loaded in. With the debugger console, I ran `pprint([i for i in sys.modules if "repro" in i])` to check the load status and got the following:
- (in `repro/bot.py`) Before loading `sanity` extension:
```
[]
```
- (in `repro/bot.py`) After loading `sanity` extension, before reloading:
```
['repro',
 'repro.command.sanity.sanity',
 'repro.command.sanity',
 'repro.command']
```
- (in `lightbulb/app.py`) After unloading `sanity` extension @ L480:
```
['repro', 'repro.command.sanity.sanity', 'repro.command']
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by PythonTryHard** [comment]
Excerpt from #lightbulb as context:
> **[20:07] Chiyu**: I came back from dinner and got a horrible idea: manually detroying the references in sys.modules for unloading. *What can possibly go wrong*
**[20:09] thomm.o | hikari enjoyer**: :bigFlushed:
**[20:11] Chiyu**: Unload `repro.command.sanity`, and destroy anything that looks like `repro\.command\.sanity\..+?`. *Absolutely nothing will subtly break and require another 3 hours of my attention*

Turns out on my full bot, manually deleting the remnants doesn't solve it. It works on the minimal reproducible somehow though, so I decided that this wasn't a good way forward.

I decided to further trace down the cause and was able to find out that in the during reloading, somehow the `Plugin` object of interest was not destroyed along with its old `CommandLike`s. And when the plugin is added again via `add_plugin()`, new commands are added in causing the traceback.
