### ISSUE TITLE
Default help command always returns exception on latest release

### ISSUE THREAD

**Issue by rainyDayDevs** [tandemdude/hikari-lightbulb#310]
### Steps to reproduce

1. Run the default "help" prefix command on any bot running the latest release of hikari and hikari-lightbulb (this can be reproduced using the example bot scripts as well)

### Expected result

The help command response

### Actual result

```
E 2023-04-06 07:04:15,537 hikari.event_manager: an exception occurred handling an event (DMMessageCreateEvent)
Traceback (most recent call last):
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/app.py", line 1037, in handle_message_create_for_prefix_commands
    await self.process_prefix_commands(context)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/app.py", line 1009, in process_prefix_commands
    await context.invoke()
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/context/base.py", line 334, in invoke
    await self.command.invoke(self)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/commands/prefix.py", line 119, in invoke
    await self(context, **kwargs)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/commands/base.py", line 712, in __call__
    return await self.callback(context, **kwargs)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/app.py", line 275, in __default_help
    await self._help_command.send_help(ctx, ctx.options.obj)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/help_command.py", line 98, in send_help
    await self._send_help(context, obj)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/help_command.py", line 102, in _send_help
    await self.send_bot_help(context)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/help_command.py", line 283, in send_bot_help
    await navigator.run(context)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/utils/nav.py", line 510, in run
    self._msg = await self._send_initial_msg(self.pages[self.current_page_index])
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/utils/nav.py", line 410, in _send_initial_msg
    buttons = await self.build_buttons()
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/utils/nav.py", line 461, in build_buttons
    button.build(buttons, disabled)
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/utils/nav.py", line 129, in build
    btn = container.add_button(self.style, self.custom_id)
AttributeError: 'MessageActionRowBuilder' object has no attribute 'add_button'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/lightbulb/app.py", line 1056, in handle_message_create_for_prefix_commands
    raise new_exc
lightbulb.errors.CommandInvocationError: An error occurred during command 'help' invocation
```

### System info

```shell
hikari-lightbulb (2.3.2)
hikari (2.0.0.dev118) [ee80448f]
located at /home/.../PycharmProjects/lightbulb-test/venv/lib/python3.10/site-packages/hikari
CPython 3.10.10 GCC 12.2.1 20230201
Linux blade 5.15.104-2-MANJARO #1 SMP PREEMPT Thu Mar 23 01:40:42 UTC 2023 x86_64
```

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by tandemdude** [comment]
This is fixed on the development branch - you can install from there until it is released
