### ISSUE TITLE
Application command creation failed for guild

### ISSUE THREAD

**Issue by bisudw** [tandemdude/hikari-lightbulb#333]
### Steps to reproduce

```
import hikari
import lightbulb

if __name__ == '__main__':
    bot = lightbulb.BotApp(
        token="xxxx",
        default_enabled_guilds="xxxx"
    )

    bot.run()
```

### Expected result

```
  oooo         o8o  oooo                            o8o       光 2.0.0.dev120 [9ade5395]
  `888         `"'  `888                            `"'       © 2021-present, davfsa - MIT license
   888 .oo.   oooo   888  oooo   .oooo.   oooo d8b oooo       interpreter:   CPython 3.10.6
   888P"Y88b  `888   888 .8P'   `P  )88b  `888""8P `888       running on:    x86_64 Linux 5.19.0-46-generic
   888   888   888   888888.     .oP"888   888      888       installed at:  /home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/hikari
   888   888   888   888 `88b.  d8(  888   888      888       documentation: https://docs.hikari-py.dev/en/2.0.0.dev120
  o888o o888o o888o o888o o888o `Y888""8o d888b    o888o      support:       https://discord.gg/Jx4cNGG

Thank you for using lightbulb!
W 2023-07-25 13:13:36,110 hikari.ux: You are running on optimization level 0 (no optimizations), which may slow down your application. For production, consider using at least level 1 optimization by passing `-O` to the python interpreter call
I 2023-07-25 13:13:36,585 hikari.bot: you can start 998 sessions before the next window which starts at 2023-07-26 13:07:45.227989+05:30; planning to start 1 session... 
I 2023-07-25 13:13:37,518 hikari.gateway.0: shard is ready: 1 guilds, iLensIoTBot#5572 (1133300879890579490), session 'f9d64508e777b42b2332e3574e2b0fdc' on v10 gateway
I 2023-07-25 13:13:37,995 lightbulb.internal: Processing guild application commands
I 2023-07-25 13:13:37,995 lightbulb.internal: Processing global application commands
I 2023-07-25 13:13:38,498 lightbulb.internal: Application command processing completed
I 2023-07-25 13:13:38,498 hikari.bot: started successfully in approx 2.38 seconds

```

### Actual result

```
   oooo         o8o  oooo                            o8o       光 2.0.0.dev120 [9ade5395]
  `888         `"'  `888                            `"'       © 2021-present, davfsa - MIT license
   888 .oo.   oooo   888  oooo   .oooo.   oooo d8b oooo       interpreter:   CPython 3.10.6
   888P"Y88b  `888   888 .8P'   `P  )88b  `888""8P `888       running on:    x86_64 Linux 5.19.0-46-generic
   888   888   888   888888.     .oP"888   888      888       installed at:  /home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/hikari
   888   888   888   888 `88b.  d8(  888   888      888       documentation: https://docs.hikari-py.dev/en/2.0.0.dev120
  o888o o888o o888o o888o o888o `Y888""8o d888b    o888o      support:       https://discord.gg/Jx4cNGG

Thank you for using lightbulb!
W 2023-07-25 13:15:32,047 hikari.ux: You are running on optimization level 0 (no optimizations), which may slow down your application. For production, consider using at least level 1 optimization by passing `-O` to the python interpreter call
I 2023-07-25 13:15:32,573 hikari.bot: you can start 994 sessions before the next window which starts at 2023-07-26 13:07:45.287686+05:30; planning to start 1 session... 
I 2023-07-25 13:15:33,618 hikari.gateway.0: shard is ready: 1 guilds, iLensIoTBot#5572 (1133300879890579490), session '5a69ae8501619612e0ea94da27dd2b25' on v10 gateway
I 2023-07-25 13:15:34,083 lightbulb.internal: Processing guild application commands
E 2023-07-25 13:15:34,619 hikari.event_manager: an exception occurred handling an event (StartedEvent)
Traceback (most recent call last):
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/lightbulb/app.py", line 385, in _manage_application_commands
    await internal.manage_application_commands(self)
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/lightbulb/internal.py", line 283, in manage_application_commands
    cmds_to_declare = await _get_guild_commands_to_set(app, guild_id)
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/lightbulb/internal.py", line 164, in _get_guild_commands_to_set
    existing_commands = await app.rest.fetch_application_commands(app.application, guild_id)
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/hikari/impl/rest.py", line 3702, in fetch_application_commands
    response = await self._request(route, query=query)
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/hikari/impl/rest.py", line 732, in _request
    await aio.first_completed(request_task, self._close_event.wait())
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/hikari/internal/aio.py", line 135, in first_completed
    await next(iterator)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/hikari/impl/rest.py", line 880, in _perform_request
    raise await net.generate_error_response(response)
hikari.errors.ForbiddenError: Forbidden 403: (50001) 'Missing Access' for https://discord.com/api/v10/applications/1133300879890579490/guilds/3/commands?with_localizations=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/lightbulb/app.py", line 390, in _manage_application_commands
    raise errors.ApplicationCommandCreationFailed(
lightbulb.errors.ApplicationCommandCreationFailed: Application command creation failed for guild '3'. Is your bot in the guild and was it invited with the 'applications.commands' scope?
I 2023-07-25 13:15:34,623 hikari.bot: started successfully in approx 2.57 seconds


```

### System info

```shell
hikari-lightbulb (2.3.3)
hikari (2.0.0.dev120) [9ade5395]
located at /home/biswa/PycharmProjects/BOT-Jarvis/.venv/lib/python3.10/site-packages/hikari
CPython 3.10.6 GCC 11.3.0
Linux biswa-laptop 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64

```
```


### Further info

_No response_

### Checklist

- [X] I have made sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by lzgirlcat** [comment]
user error, not a bug
looking at the logs I'm assuming you're passing in the guild as a str of the id
this argument accepts a list of integers so for example `[123456789, 987654321]`
